release:clean
	gcc smash.c -Wall -Werror -o smash
debug:clean
	gcc smash.c -Wall -D debug -g -o smash
bypass:clean
	gcc smash.c -Wall -g -o smash
run:
	/home/cs537-1/tests/P3/runtests -c
clean:
	rm -rf smash