on: [push]
jobs:
    build_and_static_analysis:
      runs-on: ubuntu-latest
      container:
        image: logavaseekar/cs537-tester:latest
      steps:
        - name: Checkout the repo
          uses: actions/checkout@v3
        - run: make
        - run: make clean
